/datum/voicepack/male/crimsondragon
	preview = list("jump", "pain", "groan", "huh", "laugh", "chuckle", "painmoan", "painscream", "paincrit", "giggle", "sigh")

/datum/voicepack/male/crimsondragon/get_sound(soundin, modifiers)
	var/used
	switch(soundin)
		if("attack")
			used = list('sound/vo/male/crimsondragon/attack1.ogg', 'sound/vo/male/crimsondragon/attack2.ogg', 'sound/vo/male/crimsondragon/attack3.ogg', 'sound/vo/male/crimsondragon/attack4.ogg', 'sound/vo/male/crimsondragon/attack5.ogg', 'sound/vo/male/crimsondragon/attack6.ogg')
		if("jump")
			used = list('sound/vo/male/crimsondragon/attack3.ogg', 'sound/vo/male/crimsondragon/attack5.ogg')
		if("pain")
			used = list('sound/vo/male/crimsondragon/pain1.ogg', 'sound/vo/male/crimsondragon/pain2.ogg', 'sound/vo/male/crimsondragon/pain3.ogg')
		if("groan")
			used = list('sound/vo/male/crimsondragon/groan1.ogg', 'sound/vo/male/crimsondragon/groan2.ogg')
		if("huh")
			used = list('sound/vo/male/crimsondragon/huh.ogg')
		if("laugh")
			used = list('sound/vo/male/crimsondragon/laugh1.ogg', 'sound/vo/male/crimsondragon/laugh2.ogg')
		if("chuckle")
			used = list('sound/vo/male/crimsondragon/chuckle1.ogg', 'sound/vo/male/crimsondragon/chuckle2.ogg')
		if("painmoan")
			used = list('sound/vo/male/crimsondragon/painmoan.ogg')
		if("painscream")
			used = list('sound/vo/male/crimsondragon/painscream.ogg')
		if("paincrit")
			used = list('sound/vo/male/crimsondragon/pain2.ogg')
		if("giggle")
			used = list('sound/vo/male/crimsondragon/giggle1.ogg','sound/vo/male/crimsondragon/giggle2.ogg')
		if("sigh")
			used = list('sound/vo/male/crimsondragon/sigh1.ogg','sound/vo/male/crimsondragon/sigh2.ogg')


	if(!used)
		used = ..(soundin, modifiers)
	return used
