/datum/voicepack/male/crimsondragon
	preview = list("jump", "pain", "groan", "hmm", "pleased", "huh", "laugh", "chuckle", "painmoan", "painscream", "groan", "paincrit")

/datum/voicepack/male/crimsondragon/get_sound(soundin, modifiers)
	var/used
	switch(soundin)
		if("attack")
			used = list('sound/vo/male/crimsondragon/attack1.ogg', 'sound/vo/male/crimsondragon/attack2.ogg', 'sound/vo/male/crimsondragon/attack3.ogg', 'sound/vo/male/crimsondragon/attack4.ogg', 'sound/vo/male/crimsondragon/attack5.ogg', 'sound/vo/male/crimsondragon/attack6.ogg')
		if("jump")
			used = list('sound/vo/male/crimsondragon/attack3.ogg', 'sound/vo/male/crimsondragon/attack5.ogg')
		if("pain")
			used = list('sound/vo/male/stern/pain (1).ogg', 'sound/vo/male/stern/pain (2).ogg', 'sound/vo/male/stern/pain (3).ogg', 'sound/vo/male/stern/pain (4).ogg', 'sound/vo/male/stern/pain (5).ogg')
		if("groan")
			used = list('sound/vo/male/stern/groan (1).ogg', 'sound/vo/male/stern/groan (2).ogg', 'sound/vo/male/stern/groan (3).ogg', 'sound/vo/male/stern/groan (4).ogg', 'sound/vo/male/stern/groan (5).ogg')
		if("hmm")
			used = list('sound/vo/male/stern/hmm (1).ogg', 'sound/vo/male/stern/hmm (2).ogg')
		if("pleased")
			used = list('sound/vo/male/stern/pleased (1).ogg', 'sound/vo/male/stern/pleased (2).ogg', 'sound/vo/male/stern/pleased (3).ogg', 'sound/vo/male/stern/pleased (4).ogg', 'sound/vo/male/stern/pleased (5).ogg', 'sound/vo/male/stern/pleased (6).ogg')
		if("huh")
			used = list('sound/vo/male/stern/huh (1).ogg')
		if("laugh")
			used = list('sound/vo/male/stern/laugh (1).ogg', 'sound/vo/male/stern/laugh (2).ogg')
		if("chuckle")
			used = list('sound/vo/male/stern/chuckle (1).ogg', 'sound/vo/male/stern/chuckle (2).ogg', 'sound/vo/male/stern/chuckle (3).ogg')
		if("painmoan")
			used = list('sound/vo/male/stern/painmoan (1).ogg', 'sound/vo/male/stern/painmoan (2).ogg','sound/vo/male/stern/painmoan (3).ogg','sound/vo/male/stern/painmoan (4).ogg')
		if("painscream")
			used = list('sound/vo/male/stern/painscream (1).ogg', 'sound/vo/male/stern/painscream (2).ogg')
		if("paincrit")
			used = list('sound/vo/male/stern/paincrit (1).ogg', 'sound/vo/male/stern/paincrit (2).ogg')
		if("snore")
			used = list('sound/vo/male/stern/snore (1).ogg', 'sound/vo/male/stern/snore (2).ogg')

	if(!used)
		used = ..(soundin, modifiers)
	return used
