/datum/voicepack/animal

/datum/voicepack/animal/get_sound(soundin, modifiers)
	switch(soundin)
		if("mrrp")
			return list('sound/vo/mobs/cat/mrrp.ogg')
		if("squeak")
			return list('sound/vo/mobs/mouse/squeak.ogg')
		if("prbt")
			return list('sound/vo/mobs/shark/prbt.ogg')
		if("hiss")
			return list('sound/vo/mobs/snake/hiss.ogg')
		if("meow")
			return list('sound/vo/mobs/cat/cat_meow1.ogg', 'sound/vo/mobs/cat/cat_meow2.ogg', 'sound/vo/mobs/cat/cat_meow3.ogg', 'sound/vo/mobs/cat/cat_meow4.ogg')
		if("caw")
			return list('sound/vo/mobs/bird/CROW_01.ogg', 'sound/vo/mobs/bird/CROW_03.ogg')
		if("peep")
			return list('sound/vo/mobs/bird/peep.ogg')
		if("hoot")
			return list('sound/vo/mobs/bird/hoot.ogg')
		if("roar")
			return list('sound/vo/mobs/cat/roar1.ogg', 'sound/vo/mobs/cat/roar2.ogg', 'sound/vo/mobs/cat/roar3.ogg', 'sound/vo/mobs/cat/roar4.ogg')
		if("howl")
			return list('sound/vo/mobs/wwolf/ehowl1.ogg', 'sound/vo/mobs/wwolf/ehowl2.ogg', 'sound/vo/mobs/wwolf/ehowl3.ogg', 'sound/vo/mobs/wwolf/ehowl4.ogg', 'sound/vo/mobs/wwolf/ehowl5.ogg')
		if("purr")
			return list('sound/vo/mobs/cat/cat_purr1.ogg', 'sound/vo/mobs/cat/cat_purr2.ogg', 'sound/vo/mobs/cat/cat_purr3.ogg', 'sound/vo/mobs/cat/cat_purr4.ogg')
		if("bark")
			return list('sound/vo/mobs/vw/bark (1).ogg', 'sound/vo/mobs/vw/bark (2).ogg', 'sound/vo/mobs/vw/bark (3).ogg', 'sound/vo/mobs/vw/bark (4).ogg', 'sound/vo/mobs/vw/bark (5).ogg', 'sound/vo/mobs/vw/bark (6).ogg', 'sound/vo/mobs/vw/bark (7).ogg')
		if("growl")
			return list('sound/vo/mobs/vw/idle (1).ogg', 'sound/vo/mobs/vw/idle (2).ogg', 'sound/vo/mobs/vw/idle (3).ogg', 'sound/vo/mobs/vw/idle (4).ogg')
		if("bleat")
			return list('sound/vo/mobs/goat/idle (1).ogg', 'sound/vo/mobs/goat/idle (2).ogg', 'sound/vo/mobs/goat/idle (3).ogg')
		if("chitter")
			return 'sound/vo/moth/mothchitter.ogg'
		if("flutter")
			return 'sound/vo/moth/moth_flutter.ogg'
		if("yip")
			return list('sound/vo/yip.ogg', 'sound/vo/yip2.ogg', 'sound/vo/yip3.ogg')
		if("oink")
			return list('modular/Creechers/sound/pig1.ogg', 'modular/Creechers/sound/pig2.ogg')
		if("bellow")
			return list('sound/vo/LizardBellow.ogg')
		if("squeal")
			return list('sound/vo/LizardSqueal.ogg')
		if("thump")
			return list('sound/vo/LizardThump.ogg')
	return null
